### ISSUE TITLE
Embed CSS not working properly

### ISSUE THREAD

**Issue by FlavienMacquignon** [FlavienMacquignon/FlavienMacquignon.github.io#15]
CSS seems to not work at all

**Comment by djmagnusa** [comment]
Fixed your css issue. You can check the pull request.

**Comment by FlavienMacquignon** [comment]
Thank's for the tips!
Not expecting anybody to come up to here to check-it out, but i definitely appreciate the support!
I'm not currently able to see your PR, it seems that you made it on your own repo; but i see the fix and i will definitely fix it.
Thank's again!

**Comment by djmagnusa** [comment]
> I'm not currently able to see your PR, it seems that you made it on your own repo; but i see the fix and i will definitely fix it.

Ohh, my bad. Just replace <style type="css"> with <style type="text/css" and you are good to go!
